// general
export const COMPONENT_LOADING = 'COMPONENT_LOADING'
export const COMPONENT_LOADED = 'COMPONENT_LOADED'

// store.js
export const HTTP_REQUEST_INCREMENT = 'HTTP_REQUEST_INCREMENT'
export const HTTP_REQUEST_DECREMENT = 'HTTP_REQUEST_DECREMENT'

// auth.js
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'
export const AUTH_FETCHED = 'AUTH_FETCHED'
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT'

